id: P415CC1F5
initial_creation_type: ocr
source_metadata:
  volumes:
    c1f222e2850f495b871748e9c2f14d96:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་སྤྱན་རས་གཟིགས་དབང་ཕྱུག་ཕྱག་སྟོང་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
